baseURL = 'https://victor99z.github.io/'
languageCode = 'en-us'
title = 'Victor Bernardes'
#theme = 'contrast-hugo'
theme = "PaperMod"
math= true
buildDrafts = true

[params]
  minimal = false
  excerpts = false
  description = "my blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  
